import unittest
from flaskr.yahoo_response_parser import parse_leagues_response, parse_teams_response
import numpy as np
import datetime

class TestYahooResponseParser(unittest.TestCase):


    def test_parse_leagues(self):
        example_leagues_response = """<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1/games/leagues" time="3715.9719467163ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
 <users count="1">
  <user>
   <guid>test_user_id</guid>
   <games count="18">
    <game>
     <game_key>222</game_key>
     <game_id>222</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2009/f1</url>
     <season>2009</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>222.l.498135</league_key>
       <league_id>498135</league_id>
       <name>Johnny Bravo</name>
       <url>https://football.fantasysports.yahoo.com/2009/f1/498135</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>12</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1262597542</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2009-09-10</start_date>
       <end_week>16</end_week>
       <end_date>2009-12-28</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2009</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>242</game_key>
     <game_id>242</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2010/f1</url>
     <season>2010</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>242.l.54796</league_key>
       <league_id>54796</league_id>
       <name>thug life</name>
       <url>https://football.fantasysports.yahoo.com/2010/f1/54796</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>12</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1294131187</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2010-09-09</start_date>
       <end_week>16</end_week>
       <end_date>2010-12-28</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2010</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>257</game_key>
     <game_id>257</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2011/f1</url>
     <season>2011</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>257.l.37493</league_key>
       <league_id>37493</league_id>
       <name>Think with your dipstick</name>
       <url>https://football.fantasysports.yahoo.com/2011/f1/37493</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1325930110</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2011-09-08</start_date>
       <end_week>16</end_week>
       <end_date>2011-12-26</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2011</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>273</game_key>
     <game_id>273</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2012/f1</url>
     <season>2012</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>273.l.11763</league_key>
       <league_id>11763</league_id>
       <name>RIght in the jejunum</name>
       <url>https://football.fantasysports.yahoo.com/2012/f1/11763</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1357338425</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2012-09-05</start_date>
       <end_week>16</end_week>
       <end_date>2012-12-24</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2012</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>314</game_key>
     <game_id>314</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2013/f1</url>
     <season>2013</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>314.l.72103</league_key>
       <league_id>72103</league_id>
       <name>Homies in my backpack</name>
       <url>https://football.fantasysports.yahoo.com/2013/f1/72103</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1388399816</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2013-09-05</start_date>
       <end_week>16</end_week>
       <end_date>2013-12-23</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2013</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>324</game_key>
     <game_id>324</game_id>
     <code>yahoops</code>
     <exception>
      <message>Invalid subresource leagues requested</message>
     </exception>
    </game>
    <game>
     <game_key>331</game_key>
     <game_id>331</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2014/f1</url>
     <season>2014</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>331.l.35354</league_key>
       <league_id>35354</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2014/f1/35354</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1420102578</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed>348_88412</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2014-09-04</start_date>
       <end_week>16</end_week>
       <end_date>2014-12-22</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2014</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>343</game_key>
     <game_id>343</game_id>
     <code>yahoops</code>
     <exception>
      <message>Invalid subresource leagues requested</message>
     </exception>
    </game>
    <game>
     <game_key>348</game_key>
     <game_id>348</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2015/f1</url>
     <season>2015</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>348.l.88412</league_key>
       <league_id>88412</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2015/f1/88412</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1452152912</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>331_35354</renew>
       <renewed>359_62508</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2015-09-10</start_date>
       <end_week>16</end_week>
       <end_date>2015-12-28</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2015</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>356</game_key>
     <game_id>356</game_id>
     <code>yahoops</code>
     <exception>
      <message>Invalid subresource leagues requested</message>
     </exception>
    </game>
    <game>
     <game_key>359</game_key>
     <game_id>359</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2016/f1</url>
     <season>2016</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>359.l.62508</league_key>
       <league_id>62508</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2016/f1/62508</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1483604046</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>348_88412</renew>
       <renewed>371_120246</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2016-09-08</start_date>
       <end_week>16</end_week>
       <end_date>2016-12-26</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2016</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>371</game_key>
     <game_id>371</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2017/f1</url>
     <season>2017</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>371.l.120246</league_key>
       <league_id>120246</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2017/f1/120246</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1515058102</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>359_62508</renew>
       <renewed>380_709344</renewed>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2017-09-07</start_date>
       <end_week>16</end_week>
       <end_date>2017-12-25</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2017</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>380</game_key>
     <game_id>380</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2018/f1</url>
     <season>2018</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="1">
      <league>
       <league_key>380.l.709344</league_key>
       <league_id>709344</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2018/f1/709344</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1546498770</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>371_120246</renew>
       <renewed>390_99174</renewed>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2018-09-06</start_date>
       <end_week>16</end_week>
       <end_date>2018-12-24</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2018</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>390</game_key>
     <game_id>390</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2019/f1</url>
     <season>2019</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="3">
      <league>
       <league_key>390.l.99174</league_key>
       <league_id>99174</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2019/f1/99174</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1577869735</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>380_709344</renew>
       <renewed>399_43040</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2019-09-05</start_date>
       <end_week>16</end_week>
       <end_date>2019-12-23</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2019</season>
      </league>
      <league>
       <league_key>390.l.1048736</league_key>
       <league_id>1048736</league_id>
       <name>The One Where Jon Wins Money</name>
       <url>https://football.fantasysports.yahoo.com/2019/f1/1048736</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>16</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1577870100</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2019-09-05</start_date>
       <end_week>16</end_week>
       <end_date>2019-12-23</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2019</season>
      </league>
      <league>
       <league_key>390.l.1265419</league_key>
       <league_id>1265419</league_id>
       <name>Y! Fantasy Sucks</name>
       <url>https://football.fantasysports.yahoo.com/2019/f1/1265419</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>16</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1577870435</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2019-09-05</start_date>
       <end_week>16</end_week>
       <end_date>2019-12-23</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2019</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>399</game_key>
     <game_id>399</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2020/f1</url>
     <season>2020</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="3">
      <league>
       <league_key>399.l.43040</league_key>
       <league_id>43040</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2020/f1/43040</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1610006518</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>390_99174</renew>
       <renewed>406_27951</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2020-09-10</start_date>
       <end_week>16</end_week>
       <end_date>2020-12-28</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2020</season>
      </league>
      <league>
       <league_key>399.l.607548</league_key>
       <league_id>607548</league_id>
       <name>The One Where Jon Wins Money</name>
       <url>https://football.fantasysports.yahoo.com/2020/f1/607548</url>
       <logo_url></logo_url>
       <draft_status>predraft</draft_status>
       <num_teams>14</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>390_1048736</renew>
       <renewed>406_223285</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2020-09-10</start_date>
       <end_week>16</end_week>
       <end_date>2020-12-28</end_date>
       <game_code>nfl</game_code>
       <season>2020</season>
      </league>
      <league>
       <league_key>399.l.1104944</league_key>
       <league_id>1104944</league_id>
       <name>smoky seattle FFFF</name>
       <url>https://football.fantasysports.yahoo.com/2020/f1/1104944</url>
       <logo_url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/5d05ad669bcb2dec19817bceb8a0556f5a25e7185b0b4ddbd27634aa9e740f8e.jpg</logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>16</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1610005922</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew/>
       <renewed>406_882720</renewed>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>16</current_week>
       <start_week>1</start_week>
       <start_date>2020-09-10</start_date>
       <end_week>16</end_week>
       <end_date>2020-12-28</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2020</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>406</game_key>
     <game_id>406</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/2021/f1</url>
     <season>2021</season>
     <is_registration_over>1</is_registration_over>
     <is_game_over>1</is_game_over>
     <is_offseason>1</is_offseason>
     <leagues count="3">
      <league>
       <league_key>406.l.27951</league_key>
       <league_id>27951</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/2021/f1/27951</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>17</edit_key>
       <weekly_deadline/>
       <league_update_timestamp>1642058650</league_update_timestamp>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>399_43040</renew>
       <renewed>414_49991</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>17</current_week>
       <start_week>1</start_week>
       <start_date>2021-09-09</start_date>
       <end_week>17</end_week>
       <end_date>2022-01-03</end_date>
       <is_finished>1</is_finished>
       <game_code>nfl</game_code>
       <season>2021</season>
      </league>
      <league>
       <league_key>406.l.223285</league_key>
       <league_id>223285</league_id>
       <name>The One Where Jon Wins Money</name>
       <url>https://football.fantasysports.yahoo.com/2021/f1/223285</url>
       <logo_url></logo_url>
       <draft_status>predraft</draft_status>
       <num_teams>14</num_teams>
       <edit_key>17</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>399_607548</renew>
       <renewed>414_317610</renewed>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>17</current_week>
       <start_week>1</start_week>
       <start_date>2021-09-09</start_date>
       <end_week>17</end_week>
       <end_date>2022-01-03</end_date>
       <game_code>nfl</game_code>
       <season>2021</season>
      </league>
      <league>
       <league_key>406.l.882720</league_key>
       <league_id>882720</league_id>
       <name>smoky seattle FFFF</name>
       <url>https://football.fantasysports.yahoo.com/2021/f1/882720</url>
       <logo_url></logo_url>
       <draft_status>predraft</draft_status>
       <num_teams>9</num_teams>
       <edit_key>17</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>399_1104944</renew>
       <renewed>414_483820</renewed>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>17</current_week>
       <start_week>1</start_week>
       <start_date>2021-09-09</start_date>
       <end_week>17</end_week>
       <end_date>2022-01-03</end_date>
       <game_code>nfl</game_code>
       <season>2021</season>
      </league>
     </leagues>
    </game>
    <game>
     <game_key>408</game_key>
     <game_id>408</game_id>
     <code>nfls</code>
     <exception>
      <message>Invalid subresource leagues requested</message>
     </exception>
    </game>
    <game>
     <game_key>414</game_key>
     <game_id>414</game_id>
     <name>Football</name>
     <code>nfl</code>
     <type>full</type>
     <url>https://football.fantasysports.yahoo.com/f1</url>
     <season>2022</season>
     <is_registration_over>0</is_registration_over>
     <is_game_over>0</is_game_over>
     <is_offseason>0</is_offseason>
     <is_live_draft_lobby_active>1</is_live_draft_lobby_active>
     <leagues count="3">
      <league>
       <league_key>414.l.49991</league_key>
       <league_id>49991</league_id>
       <name>Chyea In Da Buildin</name>
       <url>https://football.fantasysports.yahoo.com/f1/49991</url>
       <logo_url></logo_url>
       <draft_status>postdraft</draft_status>
       <num_teams>10</num_teams>
       <edit_key>1</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>406_27951</renew>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>1</current_week>
       <start_week>1</start_week>
       <start_date>2022-09-08</start_date>
       <end_week>17</end_week>
       <end_date>2023-01-02</end_date>
       <game_code>nfl</game_code>
       <season>2022</season>
      </league>
      <league>
       <league_key>414.l.317610</league_key>
       <league_id>317610</league_id>
       <name>The One Where Jon Wins Money</name>
       <url>https://football.fantasysports.yahoo.com/f1/317610</url>
       <logo_url></logo_url>
       <draft_status>predraft</draft_status>
       <num_teams>14</num_teams>
       <edit_key>1</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>406_223285</renew>
       <renewed/>
       <felo_tier>silver</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>1</current_week>
       <start_week>1</start_week>
       <start_date>2022-09-08</start_date>
       <end_week>17</end_week>
       <end_date>2023-01-02</end_date>
       <game_code>nfl</game_code>
       <season>2022</season>
      </league>
      <league>
       <league_key>414.l.483820</league_key>
       <league_id>483820</league_id>
       <name>smoky seattle FFFF</name>
       <url>https://football.fantasysports.yahoo.com/f1/483820</url>
       <logo_url></logo_url>
       <draft_status>predraft</draft_status>
       <num_teams>9</num_teams>
       <edit_key>1</edit_key>
       <weekly_deadline/>
       <league_update_timestamp/>
       <scoring_type>head</scoring_type>
       <league_type>private</league_type>
       <renew>406_882720</renew>
       <renewed/>
       <felo_tier>bronze</felo_tier>
       <iris_group_chat_id/>
       <allow_add_to_dl_extra_pos>1</allow_add_to_dl_extra_pos>
       <is_pro_league>0</is_pro_league>
       <is_cash_league>0</is_cash_league>
       <current_week>1</current_week>
       <start_week>1</start_week>
       <start_date>2022-09-08</start_date>
       <end_week>17</end_week>
       <end_date>2023-01-02</end_date>
       <game_code>nfl</game_code>
       <season>2022</season>
      </league>
     </leagues>
    </game>
    <exceptions>
     <exception>
      <key>324</key>
      <message>Invalid subresource leagues requested</message>
     </exception>
     <exception>
      <key>343</key>
      <message>Invalid subresource leagues requested</message>
     </exception>
     <exception>
      <key>356</key>
      <message>Invalid subresource leagues requested</message>
     </exception>
     <exception>
      <key>408</key>
      <message>Invalid subresource leagues requested</message>
     </exception>
    </exceptions>
   </games>
  </user>
 </users>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5dd4bf49c4-l2x9g Sun Aug 28 17:37:12 UTC 2022 -->
"""
        result = parse_leagues_response(example_leagues_response)
        self.assertEqual(len(result), 17)
        self.assertTrue(np.array_equal(result.columns.to_numpy(), ['league_key', 'name', 'game_code','season','num_teams', 'is_finished']))
        print(result)


    def test_parse_teams_response(self):
        content = """<?xml version="1.0" encoding="UTF-8"?>
            <fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/leagues;league_keys=414.l.1425310/standings" time="62.927961349487ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
            <leagues count="1">
            <league>
            <league_key>414.l.1425310</league_key>
            <league_id>1425310</league_id>
            <name>Seattle 2022</name>
            <url>https://football.fantasysports.yahoo.com/f1/1425310</url>
            <logo_url></logo_url>
            <password/>
            <draft_status>postdraft</draft_status>
            <num_teams>10</num_teams>
            <edit_key>2</edit_key>
            <weekly_deadline/>
            <league_update_timestamp>1663394907</league_update_timestamp>
            <scoring_type>head</scoring_type>
            <league_type>private</league_type>
            <renew/>
            <renewed/>
            <felo_tier>silver</felo_tier>
            <iris_group_chat_id/>
            <short_invitation_url>https://football.fantasysports.yahoo.com/f1/1425310/invitation?key=09e8210f558465dd&amp;ikey=f0ece576cf158de5</short_invitation_url>
            <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
            <is_pro_league>0</is_pro_league>
            <is_cash_league>0</is_cash_league>
            <current_week>2</current_week>
            <start_week>1</start_week>
            <start_date>2022-09-08</start_date>
            <end_week>17</end_week>
            <end_date>2023-01-02</end_date>
            <game_code>nfl</game_code>
            <season>2022</season>
            <standings>
                <teams count="10">
                <team>
                <team_key>414.l.1425310.t.2</team_key>
                <team_id>2</team_id>
                <name>CHAZ Michael Michael's</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/2</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_5_c.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>4</waiver_priority>
                <number_of_moves>4</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>3</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/2/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>2</manager_id>
                    <nickname>Parker</nickname>
                    <guid>FQQQR6ZAAEY7XZ5KSTVQT34PVE</guid>
                    <image_url>https://s.yimg.com/ag/images/4586/37995503444_1af450_64sq.jpg</image_url>
                    <felo_score>753</felo_score>
                    <felo_tier>gold</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>160.46</total>
                </team_points>
                <team_standings>
                <rank>1</rank>
                <playoff_seed>1</playoff_seed>
                <outcome_totals>
                    <wins>1</wins>
                    <losses>0</losses>
                    <ties>0</ties>
                    <percentage>1.000</percentage>
                </outcome_totals>
                <streak>
                    <type>win</type>
                    <value>1</value>
                </streak>
                <points_for>160.46</points_for>
                <points_against>110</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.1</team_key>
                <team_id>1</team_id>
                <name>39th St 69s</name>
                <is_owned_by_current_login>1</is_owned_by_current_login>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/1</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/761b06927e1bcfb1d520223432db1f77b2a30cc5edc45a0435cb2037a248e110.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>10</waiver_priority>
                <number_of_moves>2</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>2</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>C-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/1/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>1</manager_id>
                    <nickname>Chris A</nickname>
                    <guid>test_user_id</guid>
                    <is_commissioner>1</is_commissioner>
                    <is_current_login>1</is_current_login>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>546</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>121.48</total>
                </team_points>
                <team_standings>
                <rank>2</rank>
                <playoff_seed>2</playoff_seed>
                <outcome_totals>
                    <wins>1</wins>
                    <losses>0</losses>
                    <ties>0</ties>
                    <percentage>1.000</percentage>
                </outcome_totals>
                <streak>
                    <type>win</type>
                    <value>1</value>
                </streak>
                <points_for>121.48</points_for>
                <points_against>103.5</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.6</team_key>
                <team_id>6</team_id>
                <name>Ballard Locks Jocks</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/6</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_4_e.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>3</waiver_priority>
                <number_of_moves>0</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>C</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/6/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>6</manager_id>
                    <nickname>Elizabeth</nickname>
                    <guid>H6KB55XUHTYM6A7NGUQSC57Q3Y</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>639</felo_score>
                    <felo_tier>silver</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>109.82</total>
                </team_points>
                <team_standings>
                <rank>3</rank>
                <playoff_seed>3</playoff_seed>
                <outcome_totals>
                    <wins>1</wins>
                    <losses>0</losses>
                    <ties>0</ties>
                    <percentage>1.000</percentage>
                </outcome_totals>
                <streak>
                    <type>win</type>
                    <value>1</value>
                </streak>
                <points_for>109.82</points_for>
                <points_against>96.8</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.7</team_key>
                <team_id>7</team_id>
                <name>Shawn O’Donnell O’Connors</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/7</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_7_d.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>6</waiver_priority>
                <number_of_moves>2</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>2</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/7/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>7</manager_id>
                    <nickname>Mitch</nickname>
                    <guid>7CP5MFVXAMFA3L4ITAHDWEL6CE</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>590</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>106.58</total>
                </team_points>
                <team_standings>
                <rank>4</rank>
                <playoff_seed>4</playoff_seed>
                <outcome_totals>
                    <wins>1</wins>
                    <losses>0</losses>
                    <ties>0</ties>
                    <percentage>1.000</percentage>
                </outcome_totals>
                <streak>
                    <type>win</type>
                    <value>1</value>
                </streak>
                <points_for>106.58</points_for>
                <points_against>96.32</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.5</team_key>
                <team_id>5</team_id>
                <name>Madison Valley Playays</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/5</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_11_m.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>7</waiver_priority>
                <number_of_moves>1</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>1</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>D+</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/5/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>5</manager_id>
                    <nickname>Monika</nickname>
                    <guid>AFH5ONVUHMN7BC6HZ37NYYDZXQ</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>558</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>99.02</total>
                </team_points>
                <team_standings>
                <rank>5</rank>
                <playoff_seed>5</playoff_seed>
                <outcome_totals>
                    <wins>1</wins>
                    <losses>0</losses>
                    <ties>0</ties>
                    <percentage>1.000</percentage>
                </outcome_totals>
                <streak>
                    <type>win</type>
                    <value>1</value>
                </streak>
                <points_for>99.02</points_for>
                <points_against>91.62</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.4</team_key>
                <team_id>4</team_id>
                <name>Kirkland Cousins</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/4</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_3_d.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>8</waiver_priority>
                <number_of_moves>1</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>1</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/4/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>4</manager_id>
                    <nickname>Daniel</nickname>
                    <guid>B7DMW3SWDAKY7Q7VJE2B7DCJSA</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>591</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>110.00</total>
                </team_points>
                <team_standings>
                <rank>6</rank>
                <playoff_seed>6</playoff_seed>
                <outcome_totals>
                    <wins>0</wins>
                    <losses>1</losses>
                    <ties>0</ties>
                    <percentage>.000</percentage>
                </outcome_totals>
                <streak>
                    <type>loss</type>
                    <value>1</value>
                </streak>
                <points_for>110.00</points_for>
                <points_against>160.46</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.3</team_key>
                <team_id>3</team_id>
                <name>Central Thiccstrict</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/3</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_9.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>9</waiver_priority>
                <number_of_moves>1</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>1</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/3/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>3</manager_id>
                    <nickname>Harry</nickname>
                    <guid>Q65XUNRSXX7AXPRUCB7GLLXHEE</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>589</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>103.50</total>
                </team_points>
                <team_standings>
                <rank>7</rank>
                <playoff_seed>7</playoff_seed>
                <outcome_totals>
                    <wins>0</wins>
                    <losses>1</losses>
                    <ties>0</ties>
                    <percentage>.000</percentage>
                </outcome_totals>
                <streak>
                    <type>loss</type>
                    <value>1</value>
                </streak>
                <points_for>103.50</points_for>
                <points_against>121.48</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.8</team_key>
                <team_id>8</team_id>
                <name>Puget Sound Reach Around</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/8</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_3_v.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>2</waiver_priority>
                <number_of_moves>1</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>1</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/8/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>8</manager_id>
                    <nickname>Drew</nickname>
                    <guid>ZMA2DHUEA2AUSN36B5OPTHP2RA</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>589</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>96.80</total>
                </team_points>
                <team_standings>
                <rank>8</rank>
                <playoff_seed>8</playoff_seed>
                <outcome_totals>
                    <wins>0</wins>
                    <losses>1</losses>
                    <ties>0</ties>
                    <percentage>.000</percentage>
                </outcome_totals>
                <streak>
                    <type>loss</type>
                    <value>1</value>
                </streak>
                <points_for>96.80</points_for>
                <points_against>109.82</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.9</team_key>
                <team_id>9</team_id>
                <name>Stone Way Stoners</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/9</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_1_j.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>1</waiver_priority>
                <number_of_moves>0</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>A-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/9/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>9</manager_id>
                    <nickname>Jay</nickname>
                    <guid>5GETUBVTRKKN3DBD3FRWMTK7VE</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>588</felo_score>
                    <felo_tier>bronze</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>96.32</total>
                </team_points>
                <team_standings>
                <rank>9</rank>
                <outcome_totals>
                    <wins>0</wins>
                    <losses>1</losses>
                    <ties>0</ties>
                    <percentage>.000</percentage>
                </outcome_totals>
                <streak>
                    <type>loss</type>
                    <value>1</value>
                </streak>
                <points_for>96.32</points_for>
                <points_against>106.58</points_against>
                </team_standings>
                </team>
                <team>
                <team_key>414.l.1425310.t.10</team_key>
                <team_id>10</team_id>
                <name>Jon's Nice Team</name>
                <url>https://football.fantasysports.yahoo.com/f1/1425310/10</url>
                <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_10_j.png</url>
                </team_logo>
                </team_logos>
                <waiver_priority>5</waiver_priority>
                <number_of_moves>2</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>2</coverage_value>
                <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/f1/1425310/10/draftrecap</draft_recap_url>
                <managers>
                <manager>
                    <manager_id>10</manager_id>
                    <nickname>Jon</nickname>
                    <guid>4CL2F3K22TUY3QVDWWVMCHV45Q</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    <felo_score>735</felo_score>
                    <felo_tier>gold</felo_tier>
                </manager>
                </managers>
                <team_points>
                <coverage_type>season</coverage_type>
                <season>2022</season>
                <total>91.62</total>
                </team_points>
                <team_standings>
                <rank>10</rank>
                <outcome_totals>
                    <wins>0</wins>
                    <losses>1</losses>
                    <ties>0</ties>
                    <percentage>.000</percentage>
                </outcome_totals>
                <streak>
                    <type>loss</type>
                    <value>1</value>
                </streak>
                <points_for>91.62</points_for>
                <points_against>99.02</points_against>
                </team_standings>
                </team>
                </teams>
            </standings>
            </league>
            </leagues>
            </fantasy_content>
            <!-- fantasy-sports-api- -public-production-bf1-5d8f885ccb-db62g Sat Sep 17 17:03:30 UTC 2022 -->
            """
        start_date, start_week, end_week, season, data = parse_teams_response(content)
        self.assertEqual(start_date.strftime("%Y-%m-%d"), datetime.date(2022, 9, 8).strftime("%Y-%m-%d"))
        self.assertEqual(start_week, 1)
        self.assertEqual(end_week, 2)
        self.assertEqual(season, "2022")
        self.assertEqual(len(data), 10)
        self.assertTrue(np.array_equal(data.columns.to_numpy(), ['name', 'team_key', 'number_of_moves', 'number_of_trades', 'clinched_playoffs', 'manager_name', 'division_id', 'draft_grade', 'rank', 'points_for', 'points_against', 'wins', 'losses']))
        print(data)

if __name__ == '__main__':
    unittest.main()